spring:
  data:
    mongodb:
      uri: mongodb+srv://pov_user:pov_pwd@cluster0.bjpsr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      #uri: ${MONGODB_URI}
      database: rdbms
  datasource:
    url: jdbc:postgresql://rdbms-comparator.cluster-cymtbjk7fwn8.us-east-1.rds.amazonaws.com/rdbms
    #url: ${POSTGRES_URI}
    username: yoda
    driver-class-name: org.postgresql.Driver
    password: starwars
    type: org.postgresql.ds.PGPoolingDataSource
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  application:
    name: RDBMSComparator


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: INFO
      mongodb:
        driver: WARN

debug: false
