spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: rdbms
  datasource:
    url: ${POSTGRES_URI}
    username: yoda
    driver-class-name: org.postgresql.Driver
    password: starwars
    type: org.postgresql.ds.PGPoolingDataSource
    name: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: false
        generate_statistics: true
    generate-ddl: true
  application:
    name: RDBMSComparator
  debug: false

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
management:
  observability:
    enabled: true
  metrics:
    mongo:
      command:
        enabled: true
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include:
        - metrics
        - open-api
        - swagger-ui
server:
  max-http-request-header-size: 16KB


# /api-docs endpoint custom path
springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
  show-actuator: true




