---
mesh:
  enabled: true
services:
  - name: http
    ingress: true
    port: 80
    protocol: TCP
    targetPort: 8080
    type: ClusterIP
ingress:
  enabled: true
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 128Mi